---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsvpcpeeringmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsvpcpeeringmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - awsvpcpeeringmirrors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - azurevpcpeeringmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - azurevpcpeeringmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - azurevpcpeeringmirrors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpvpcpeeringmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpvpcpeeringmirrors/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - gcpvpcpeeringmirrors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsvolumemirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsvolumemirrors/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsvolumemirrors/status
  verbs:
  - get
  - patch
  - update
