---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - ipranges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsinstances/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - nfsinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - vpcpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - vpcpeerings/finalizers
  verbs:
  - update
- apiGroups:
  - cloud-resources.kyma-project.io
  resources:
  - vpcpeerings/status
  verbs:
  - get
  - patch
  - update
