apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AwsVpcPeering
metadata:
  labels:
    app.kubernetes.io/name: awsvpcpeering
    app.kubernetes.io/instance: awsvpcpeering-sample
    app.kubernetes.io/part-of: cloud-resources-control-plane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-resources-control-plane
  name: awsvpcpeering-sample
spec:
  # TODO(user): Add fields here
