apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: GcpVpcPeeringMirror
metadata:
  labels:
    app.kubernetes.io/name: gcpvpcpeeringmirror
    app.kubernetes.io/instance: gcpvpcpeeringmirror-sample
    app.kubernetes.io/part-of: cloud-resources-control-plane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-resources-control-plane
  name: gcpvpcpeeringmirror-sample
spec:
  # TODO(user): Add fields here
