apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVpcPeeringMirror
metadata:
  labels:
    app.kubernetes.io/name: azurevpcpeeringmirror
    app.kubernetes.io/instance: azurevpcpeeringmirror-sample
    app.kubernetes.io/part-of: cloud-resources-control-plane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-resources-control-plane
  name: azurevpcpeeringmirror-sample
spec:
  # TODO(user): Add fields here
