## Append samples of your project ##
resources:
- cloud-resources_v1beta1_nfsinstance.yaml
- cloud-resources_v1beta1_vpcpeering.yaml
- cloud-resources_v1beta1_iprange.yaml
- cloud-resources_v1beta1_scope.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
