name: E2E Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          go mod tidy
          go mod download
          go build -o bin/manager cmd/main.go
      - name: Foo
        run: |
          ls -la
          ls -la ./bin/
